name: Build
run-name: "Build #${{ github.run_number }}"

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: mvn -Dmaven.test.skip=true --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: staging

  release-github:
    name: Deploy to GitHub
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
      - uses: softprops/action-gh-release@v1
        with:
          files: ./*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}